USE patstat2010april;

CREATE TABLE TLS201_APPLN (
	APPLN_ID INT unsigned NOT NULL,
	APPLN_AUTH CHAR(2) NOT NULL,
	APPLN_NR CHAR(15) NOT NULL,
	APPLN_KIND CHAR(2),
	APPLN_FILING_DATE DATE,
	IPR_TYPE CHAR(2),
	APPLN_TITLE_LG CHAR(2),
	APPLN_ABSTRACT_LG CHAR(2),
	INTERNAT_APPLN_ID INT unsigned,
	PRIMARY KEY (APPLN_ID)
);

CREATE TABLE TLS202_APPLN_TITLE (
	APPLN_ID INT unsigned NOT NULL,
	APPLN_TITLE VARCHAR(3000) NOT NULL,
	PRIMARY KEY (APPLN_ID),
	FOREIGN KEY (APPLN_ID) REFERENCES TLS201_APPLN(APPLN_ID)
);

CREATE TABLE TLS203_APPLN_ABSTR (
	APPLN_ID INT unsigned NOT NULL,
	APPLN_ABSTRACT VARCHAR(10000) NOT NULL,
	PRIMARY KEY (APPLN_ID),
	FOREIGN KEY (APPLN_ID) REFERENCES TLS201_APPLN(APPLN_ID)
);

CREATE TABLE TLS204_APPLN_PRIOR (
	APPLN_ID INT unsigned NOT NULL,
	PRIOR_APPLN_ID INT unsigned NOT NULL,
	PRIOR_APPLN_SEQ_NR SMALLINT unsigned,
	PRIMARY KEY (APPLN_ID, PRIOR_APPLN_ID),
	FOREIGN KEY (APPLN_ID) REFERENCES TLS201_APPLN(APPLN_ID),
	FOREIGN KEY (PRIOR_APPLN_ID) REFERENCES TLS201_APPLN(APPLN_ID)
);

CREATE TABLE TLS205_TECH_REL (
	APPLN_ID INT unsigned NOT NULL,
	TECH_REL_APPLN_ID INT unsigned NOT NULL,
	PRIMARY KEY (APPLN_ID, TECH_REL_APPLN_ID),
	FOREIGN KEY (APPLN_ID) REFERENCES TLS201_APPLN(APPLN_ID),
	FOREIGN KEY (TECH_REL_APPLN_ID) REFERENCES TLS201_APPLN(APPLN_ID)
);

CREATE TABLE TLS208_DOC_STD_NMS (
	DOC_STD_NAME_ID INT unsigned NOT NULL,
	DOC_STD_NAME VARCHAR(30) NOT NULL,
	PRIMARY KEY (DOC_STD_NAME_ID)
);

CREATE TABLE TLS206_PERSON (
	PERSON_ID INT unsigned NOT NULL,
	PERSON_CTRY_CODE VARCHAR(4), -- doc says char(2) but can't fit encoded codes
	DOC_STD_NAME_ID INT unsigned,
	PERSON_NAME VARCHAR(400) NOT NULL, -- +100 from doc definition to fit encoded names
	PERSON_ADDRESS VARCHAR(500),
	PRIMARY KEY (PERSON_ID),
	FOREIGN KEY (DOC_STD_NAME_ID) REFERENCES TLS208_DOC_STD_NMS(DOC_STD_NAME_ID)
);

CREATE TABLE TLS207_PERS_APPLN (
	PERSON_ID INT unsigned NOT NULL,
	APPLN_ID INT unsigned NOT NULL,
	APPLT_SEQ_NR SMALLINT unsigned NOT NULL,
	INVT_SEQ_NR SMALLINT unsigned NOT NULL,
	UNIQUE (PERSON_ID),
	UNIQUE (APPLN_ID),
	FOREIGN KEY (PERSON_ID) REFERENCES TLS206_PERSON(PERSON_ID),
	FOREIGN KEY (APPLN_ID) REFERENCES TLS201_APPLN(APPLN_ID)
);

CREATE TABLE TLS209_APPLN_IPC (
	APPLN_ID INT unsigned NOT NULL,
	IPC_CLASS_SYMBOL CHAR(15) NOT NULL,
	IPC_CLASS_LEVEL CHAR(1) NOT NULL,
	IPC_VERSION DATE,
	IPC_VALUE CHAR(1),
	IPC_POSITION CHAR(1),
	IPC_GENER_AUTH CHAR(2),
	PRIMARY KEY (APPLN_ID, IPC_CLASS_SYMBOL, IPC_CLASS_LEVEL), -- third one ok?
	FOREIGN KEY (APPLN_ID) REFERENCES TLS201_APPLN(APPLN_ID)
);

CREATE TABLE TLS210_APPLN_N_CLS (
	APPLN_ID INT unsigned NOT NULL,
	NAT_CLASS_SYMBOL CHAR(15) NOT NULL,
	PRIMARY KEY (APPLN_ID, NAT_CLASS_SYMBOL),
	FOREIGN KEY (APPLN_ID) REFERENCES TLS201_APPLN(APPLN_ID)
);

CREATE TABLE TLS211_PAT_PUBLN (
	PAT_PUBLN_ID INT unsigned NOT NULL,
	PUBLN_AUTH CHAR(2) NOT NULL,
	PUBLN_NR CHAR(15) NOT NULL,
	PUBLN_KIND CHAR(2),
	APPLN_ID INT unsigned NOT NULL,
	PUBLN_DATE DATE,
	PUBLN_LG CHAR(2),
	PUBLN_FIRST_GRANT TINYINT unsigned,
	PRIMARY KEY (PAT_PUBLN_ID),
	FOREIGN KEY (APPLN_ID) REFERENCES TLS201_APPLN(APPLN_ID)
);

CREATE TABLE TLS214_NPL_PUBLN (
	NPL_PUBLN_ID INT unsigned NOT NULL,
	NPL_BIBLIO VARCHAR(3000),
	PRIMARY KEY (NPL_PUBLN_ID)
);

CREATE TABLE TLS212_CITATION (
	PAT_PUBLN_ID INT unsigned NOT NULL,
	CITN_ID SMALLINT unsigned NOT NULL,
	CITED_PAT_PUBLN_ID INT unsigned,
	NPL_PUBLN_ID INT unsigned,
	PAT_CITN_SEQ_NR SMALLINT unsigned,
	NPL_CITN_SEQ_NR SMALLINT unsigned,
	CITN_ORIGIN CHAR(5), -- char(3)?
	PRIMARY KEY (PAT_PUBLN_ID, CITN_ID),
	FOREIGN KEY (PAT_PUBLN_ID) REFERENCES TLS211_PAT_PUBLN(PAT_PUBLN_ID),
	FOREIGN KEY (CITED_PAT_PUBLN_ID) REFERENCES TLS211_PAT_PUBLN(PAT_PUBLN_ID),
	FOREIGN KEY (NPL_PUBLN_ID) REFERENCES TLS214_NPL_PUBLN(NPL_PUBLN_ID)
);

CREATE TABLE TLS215_CITN_CATEG (
	PAT_PUBLN_ID INT unsigned NOT NULL,
	CITN_ID SMALLINT unsigned NOT NULL,
	CITN_CATEG CHAR(1) NOT NULL,
	PRIMARY KEY (PAT_PUBLN_ID, CITN_ID, CITN_CATEG),
	FOREIGN KEY (PAT_PUBLN_ID, CITN_ID) REFERENCES TLS212_CITATION(PAT_PUBLN_ID, CITN_ID)
);

CREATE TABLE TLS216_APPLN_CONTN (
	APPLN_ID INT unsigned NOT NULL,
	PARENT_APPLN_ID INT unsigned NOT NULL,
	CONTN_TYPE CHAR(3),
	PRIMARY KEY (APPLN_ID, PARENT_APPLN_ID),
	FOREIGN KEY (APPLN_ID) REFERENCES TLS201_APPLN(APPLN_ID),
	FOREIGN KEY (PARENT_APPLN_ID) REFERENCES TLS201_APPLN(APPLN_ID)
);

CREATE TABLE TLS217_APPLN_ECLA (
	APPLN_ID INT unsigned NOT NULL,
	EPO_CLASS_AUTH CHAR(2) NOT NULL,
	EPO_CLASS_SCHEME VARCHAR(4) NOT NULL,
	EPO_CLASS_SYMBOL VARCHAR(50) NOT NULL,
	PRIMARY KEY (APPLN_ID, EPO_CLASS_AUTH, EPO_CLASS_SCHEME, EPO_CLASS_SYMBOL),
	FOREIGN KEY (APPLN_ID) REFERENCES TLS201_APPLN(APPLN_ID)
);

CREATE TABLE TLS218_DOCDB_FAM (
	APPLN_ID INT unsigned NOT NULL,
	DOCDB_FAMILY_ID INT unsigned NOT NULL,
	PRIMARY KEY (APPLN_ID, DOCDB_FAMILY_ID),
	FOREIGN KEY (APPLN_ID) REFERENCES TLS201_APPLN(APPLN_ID)
);

CREATE TABLE TLS219_INPADOC_FAM (
	APPLN_ID INT unsigned NOT NULL,
	INPADOC_FAMILY_ID INT unsigned NOT NULL,
	PRIMARY KEY (APPLN_ID, INPADOC_FAMILY_ID),
	FOREIGN KEY (APPLN_ID) REFERENCES TLS201_APPLN(APPLN_ID)
);
