USE patstat;

LOAD DATA LOCAL INFILE 'tls211_part01.txt' INTO TABLE tls211_pat_publn
	FIELDS TERMINATED BY ','
	OPTIONALLY ENCLOSED BY '"'
	LINES TERMINATED BY '\r\n'
	IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'tls211_part02.txt' INTO TABLE tls211_pat_publn
	FIELDS TERMINATED BY ','
	OPTIONALLY ENCLOSED BY '"'
	LINES TERMINATED BY '\r\n'
	IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'tls211_part03.txt' INTO TABLE tls211_pat_publn
	FIELDS TERMINATED BY ','
	OPTIONALLY ENCLOSED BY '"'
	LINES TERMINATED BY '\r\n'
	IGNORE 1 LINES;
