USE patstat;

LOAD DATA LOCAL INFILE 'tls217_part01.txt' INTO TABLE tls217_appln_ecla
	FIELDS TERMINATED BY ','
	OPTIONALLY ENCLOSED BY '"'
	LINES TERMINATED BY '\r\n'
	IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'tls217_part02.txt' INTO TABLE tls217_appln_ecla
	FIELDS TERMINATED BY ','
	OPTIONALLY ENCLOSED BY '"'
	LINES TERMINATED BY '\r\n'
	IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'tls217_part03.txt' INTO TABLE tls217_appln_ecla
	FIELDS TERMINATED BY ','
	OPTIONALLY ENCLOSED BY '"'
	LINES TERMINATED BY '\r\n'
	IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'tls217_part04.txt' INTO TABLE tls217_appln_ecla
	FIELDS TERMINATED BY ','
	OPTIONALLY ENCLOSED BY '"'
	LINES TERMINATED BY '\r\n'
	IGNORE 1 LINES;
