USE patstat;

LOAD DATA LOCAL INFILE 'tls201_part01.txt' INTO TABLE tls201_appln
	FIELDS TERMINATED BY ','
	OPTIONALLY ENCLOSED BY '"'
	LINES TERMINATED BY '\r\n'
	IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'tls201_part02.txt' INTO TABLE tls201_appln
	FIELDS TERMINATED BY ','
	OPTIONALLY ENCLOSED BY '"'
	LINES TERMINATED BY '\r\n'
	IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'tls201_part03.txt' INTO TABLE tls201_appln
	FIELDS TERMINATED BY ','
	OPTIONALLY ENCLOSED BY '"'
	LINES TERMINATED BY '\r\n'
	IGNORE 1 LINES;
