USE patstat;

LOAD DATA LOCAL INFILE 'tls206_part01.txt' INTO TABLE tls206_person
	CHARACTER SET 'latin1'
	FIELDS TERMINATED BY ','
	OPTIONALLY ENCLOSED BY '"'
	LINES TERMINATED BY '\r\n'
	IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'tls206_part02.txt' INTO TABLE tls206_person
	CHARACTER SET 'latin1'
	FIELDS TERMINATED BY ','
	OPTIONALLY ENCLOSED BY '"'
	LINES TERMINATED BY '\r\n'
	IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'tls206_part03.txt' INTO TABLE tls206_person
	CHARACTER SET 'latin1'
	FIELDS TERMINATED BY ','
	OPTIONALLY ENCLOSED BY '"'
	LINES TERMINATED BY '\r\n'
	IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'tls206_part04.txt' INTO TABLE tls206_person
	CHARACTER SET 'latin1'
	FIELDS TERMINATED BY ','
	OPTIONALLY ENCLOSED BY '"'
	LINES TERMINATED BY '\r\n'
	IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'tls206_part05.txt' INTO TABLE tls206_person
	CHARACTER SET 'latin1'
	FIELDS TERMINATED BY ','
	OPTIONALLY ENCLOSED BY '"'
	LINES TERMINATED BY '\r\n'
	IGNORE 1 LINES;
